export class House {
  public id ?: number;
  public headline : String;
  public description : String;
  public price : number;
  public address : String;
  public space : number;
  public housetype : String;
  public hasWifi : boolean;
  public hasTV : boolean;
  public hasDryer : boolean;
  public isFamilyFriendly : boolean;
  public thumbnail_image ?: String;
  public houseImg1 ?: String;
  public houseImg2 ?: String;
  public houseImg3 ?: String;
  public houseImg4 ?: String;
  public houseImg5 ?: String;
}
